##name: Android CI
##
##on:
##  push:
##    branches: [ "master" ]
##  pull_request:
##    branches: [ "master" ]
##
##jobs:
##  build:
##
##    runs-on: ubuntu-latest
##
##    steps:
##    - uses: actions/checkout@v3
##    - name: set up JDK 11
##      uses: actions/setup-java@v3
##      with:
##        java-version: '11'
##        distribution: 'temurin'
##        cache: gradle
##
##    - name: Grant execute permission for gradlew
##      run: chmod +x gradlew
##    - name: Build with Gradle
##      run: ./gradlew build
#name: Build and Test Android App
#
#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
#
##  push:
##    branches: ["main", "dev", "master"]
##  pull_request:
##    branches: ["main", "dev", "master"]
#
#jobs:
#  build-and-test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#      - uses: actions/checkout@v3
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Grant execute permission for gradlew
#        uses: actions/checkout@v3
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        uses: actions/checkout@v3
#        run: ./gradlew build
#
#      #      - name: Setup JDK
#      #        uses: actions/setup-java@v2
#      #        with:
#      #          java-version: '11'
##      - name: set up JDK 11
##          uses: actions/setup-java@v2
##          with:
##            java-version: '11'
##            distribution: 'temurin'
##            cache: gradle
#
#      - name: Run lint
#        uses: actions/checkout@v3
#        run: ./gradlew lintDebug
#        continue-on-error: true
#
#      - name: Run tests
#        uses: actions/checkout@v3
#        run: ./gradlew testDebug
#        continue-on-error: true
#
#      - name: Build APK
#        uses: actions/checkout@v3
#        if: ${{ success() }}
#        run: ./gradlew assembleDebug --console=plain
#
#      - name: Save APK to artifacts
#        uses: actions/upload-artifact@v2
#        if: ${{ success() }}
#        with:
#          name: ${{ github.event_name }}-app
#          path: app/build/outputs/apk/debug/app-debug.apk
