
name: Build

on:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0

      - name: Echo previoustag
        run: echo ${{ steps.previoustag.outputs.tag }}

      - name: Echo name
        run: echo ${{ github.ref_name }}

      - name: Echo id
        run: echo ${{ github.run_number }}




#      - name: Generate release tag
#        id: generate_release_tag
#        uses: amitsingh-007/next-release-tag@v4.0.0
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          tag_prefix: '1.6.13'
#          tag_template: "d.i"
#
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          tag_name: ${{ steps.previoustag.outputs.tag }}
          release_name: Release ${{ steps.previoustag.outputs.tag }}




      - name: Build APK
        if: ${{ success() }}
        run: ./gradlew app:assemble -PversionName="${{ steps.previoustag.outputs.tag }}.${{ github.run_number }}" -PversionCode="${{ github.run_number }}" --no-daemon

      - name: Build ABB
        if: ${{ success() }}
        run: ./gradlew app:bundleCmlRelease -PversionName="${{ steps.previoustag.outputs.tag }}.${{ github.run_number }}" -PversionCode="${{ github.run_number }}" --no-daemon

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            app/build/outputs/**/*.apk
            app/build/outputs/**/*.aab
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive
