
name: Create build

on:
  push:
    branches:
      - main
      - master
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - uses: actions-ecosystem/action-get-latest-tag@v1
        id: get-latest-tag

      - name: Echo get-latest-tag
        run: echo ${{ steps.get-latest-tag.outputs.tag }}

      - name: Echo name
        run: echo ${{ github.ref_name }}

      - name: Echo id
        run: echo ${{ github.run_number }}

      - name: Build APK
        if: ${{ success() }}
        run: ./gradlew app:assemble -PversionName="${{ steps.get-latest-tag.outputs.tag }}.${{ github.run_number }}" -PversionCode="${{ github.run_number }}" --no-daemon

      - name: Build ABB
        if: ${{ success() }}
        run: ./gradlew app:bundleRelease -PversionName="${{ steps.get-latest-tag.outputs.tag }}.${{ github.run_number }}" -PversionCode="${{ github.run_number }}" --no-daemon

      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: true
          tag_name: ${{ steps.get-latest-tag.outputs.tag }}.${{ github.run_number }}
          release_name: Release ${{ steps.get-latest-tag.outputs.tag }}.${{ github.run_number }}

#      - name: Save APK to artifacts
#        if: ${{ success() }}
#        uses: actions/upload-artifact@v2
#        with:
#          name: build-${{ steps.get-latest-tag.outputs.tag }}.${{ github.run_number }}
#          path: |
#            app/build/outputs/**/*.apk
#            app/build/outputs/**/*.aab
#
#      -  name: Download artifacts
#         id: download_artifact
#         uses: actions/download-artifact@v3
#         with:
#           name: build-${{ steps.get-latest-tag.outputs.tag }}.${{ github.run_number }}
#           path: artifact
#
#      - name: Echo Download artifacts
#        run: echo ${{ steps.download_artifact.outputs.download-path }}
      - name: Save APK to artifacts
        if: ${{ success() }}
        run: |
          mkdir artifacts
          find -regex '.+\.((apk)|(aab))' -exec cp -t ./artifacts {} +
          zip -r builds.zip artifacts
          ls
          cd artifacts
          ls


      - name: Upload APK to Release
        uses: shogo82148/actions-upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts
          asset_name: builds
          asset_content_type: application/vnd.android.package-archive
